// OpenNR -- a ReShade add-on that runs a small image-enhancement network on the game's frame.
//
// A frame, in order:
//   1. stage      the frame, sampled down to the network's resolution, into 16 input channels
//   2. network    19 convolutions (opennr_model.hpp), on the game's GPU or on another one
//   3. composite  the network's correction lifted back to the output resolution and added to
//                 the full-resolution frame, with Strength, the Model B/C grade, and the view
//
// When it can, the add-on does this before the game draws its HUD, so the HUD is drawn over the
// corrected picture instead of being corrected with it. D3D11 and D3D12; Vulkan is experimental.
//
// Copyright (c) 2026 MakeDecisionWorth. MIT licence, see LICENSE.

#include <imgui.h>
#include <reshade.hpp>

#include "opennr_model.hpp"
#include "opennr_remote.hpp"
#include "opennr_spirv.hpp"     // generated by build.ps1

#include <dxgi.h>
#include <d3d11_1.h>    // SwapDeviceContextState, for the correction before the HUD
#include <d3d12.h>      // ID3D12Device::GetAdapterLuid

#include <d3dcompiler.h>

#include <algorithm>
#include <atomic>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

#pragma comment(lib, "d3dcompiler.lib")

using namespace reshade::api;

namespace {

constexpr const char* kVersion = "0.1.0";

// The network's resolution: at least 320 and a multiple of 64 on each side.
uint32_t align_extent(uint32_t n) {
    const uint32_t a = (n + 63) / 64 * 64;
    return a < 320 ? 320 : a;
}

struct Ctx {
    device* dev = nullptr;
    uint32_t ow = 0, oh = 0;          // the output
    format fmt = format::unknown;     // the back buffer's
    uint32_t model = 0xffffffffu;     // which model `net` holds
    uint32_t w = 0, h = 0;            // the network
    uint32_t frame = 0;

    opennr::Network net;
    pipeline stage_pso = {}, comp_pso = {}, conv_pso = {}, pool_pso = {}, upcat_pso = {};
    pipeline glob_pso = {};
    // One layout for every kernel on D3D. Vulkan types its descriptors, so there the two kernels
    // that read the frame get layouts of their own; on D3D all three are the same handle.
    pipeline_layout layout = {}, layout_stage = {}, layout_comp = {};
    pipeline_layout layout_for(pipeline p) const {
        return p == stage_pso ? layout_stage : p == comp_pso ? layout_comp : layout;
    }
    // the middle block's bias for this frame, when the model has a whole-frame branch
    resource gbias = {};
    resource_view gbias_srv = {}, gbias_uav = {};

    resource chans = {}, head = {}, A = {}, B = {}, skip[8] = {}, scratch = {};
    resource src_copy = {};           // the frame to read; the back buffer itself cannot be
    resource_view src_copy_srv = {};
    resource_view chans_uav = {}, chans_srv = {}, head_uav = {}, head_srv = {};
    resource_view A_uav = {}, A_srv = {}, B_uav = {}, B_srv = {};
    resource_view skip_uav[8] = {}, skip_srv[8] = {}, scratch_uav = {};
    bool ready = false, failed = false;

    // What each resource the add-on owns was last used as, so barriers can be issued on D3D12
    // and Vulkan (D3D11 tracks this itself). Every resource also has a home state, and `settle`
    // returns everything there at the end of the add-on's work in a command list: on D3D12 the
    // work lands in the game's lists on some frames and in ReShade's on others, and those do
    // not necessarily run in the order they were recorded. `forget` is called before every
    // destroy, so a handle the game is given later never inherits a stale entry.
    struct Tracked { uint64_t h; resource_usage cur, home; };
    std::vector<Tracked> states;
    void forget(resource r) {
        for (size_t i = 0; i < states.size(); ++i)
            if (states[i].h == r.handle) {
                states[i] = states.back();
                states.pop_back();
                return;
            }
    }
    void track(resource r, resource_usage u) {
        if (!r.handle) return;
        for (auto& s : states) if (s.h == r.handle) { s.cur = s.home = u; return; }
        states.push_back({r.handle, u, u});
    }
    void use(command_list* cmd, resource r, resource_usage u) {
        if (!r.handle) return;
        for (auto& s : states)
            if (s.h == r.handle) {
                if (s.cur != u || u == resource_usage::unordered_access)
                    cmd->barrier(r, s.cur, u);
                s.cur = u;
                return;
            }
    }
    void settle(command_list* cmd) {
        for (auto& s : states)
            if (s.cur != s.home) {
                cmd->barrier(resource{s.h}, s.cur, s.home);
                s.cur = s.home;
            }
    }
    void use_view(command_list* cmd, resource_view v, resource_usage u) {
        if (!v.handle) return;
        use(cmd, opennr::is_buffer_stand_in(v) ? resource{v.handle} : dev->get_resource_from_view(v),
            u);
    }

    device_api api = device_api::d3d11;

    // CPU data into one of our buffers. On D3D11 an UpdateSubresource, in order with everything
    // else. Elsewhere it goes through an upload buffer and a copy recorded in the command list,
    // one upload buffer per ring slot so none is rewritten while the GPU may still read it.
    resource up[3] = {};
    uint64_t up_size = 0;
    uint32_t up_slot = 0;
    void upload(device* d, command_list* cmd, const void* data, uint64_t size, resource dst) {
        if (api == device_api::d3d11 || !cmd) {
            d->update_buffer_region(data, dst, 0, size);
            return;
        }
        if (up_size < size) {
            for (resource& r : up)
                if (r.handle) { d->destroy_resource(r); r = {}; }
            up_size = 0;
            for (resource& r : up)
                if (!d->create_resource(resource_desc(size, memory_heap::cpu_to_gpu,
                                                      resource_usage::copy_source),
                                        nullptr, resource_usage::copy_source, &r))
                    return;
            up_size = size;
        }
        resource u = up[up_slot];
        up_slot = (up_slot + 1) % 3;
        void* p = nullptr;
        if (!d->map_buffer_region(u, 0, size, map_access::write_only, &p)) return;
        std::memcpy(p, data, size_t(size));
        d->unmap_buffer_region(u);
        use(cmd, dst, resource_usage::copy_dest);
        cmd->copy_buffer_region(u, 0, dst, 0, size);
    }

    // GPU timestamps either side of the work, read back a few frames later so nothing stalls
    static constexpr uint32_t RING = 4;
    query_heap timer = {};
    uint64_t tick_hz = 0;
    uint32_t slot = 0;
    bool slot_used[RING] = {};
    double gpu_ms = 0.0;        // exponential mean, in milliseconds
    bool untimed = false;       // the last frame could not be timed (D3D12, before the HUD)

    void destroy();
    bool build(device* d, uint32_t OW, uint32_t OH, format target_fmt);
};

Ctx g;

// ---- the settings, each saved in ReShade.ini under [OpenNR]
uint32_t g_strength = 100;      // Strength, percent
uint32_t g_tone = 100;          // Local Tone Strength, percent
uint32_t g_structure = 100;     // Local Structure Strength, percent
uint32_t g_model = 0;           // Model A/B/C: the colour grade, and which of the model's outputs
uint32_t g_model_idx = 0;       // Correction Model: 0 = 1 pass, 1 = 2 passes
uint32_t g_view = 0;            // View (not saved): 0 final frame, 1 correction x20, 2 source

// The two Correction Models, each a separate network (one pass costs the same as the other),
// in folders beside the add-on.
const char* kModelDirs[] = {"OpenNR\\1pass", "OpenNR\\2pass"};
const char* kModelLabels[] = {"1 pass", "2 passes"};
constexpr uint32_t kModelCount = 2;

HMODULE g_module = nullptr;
// The effect runtime `render_before_interface` asks for its effects; set at begin-effects.
effect_runtime* g_rt = nullptr;

std::string module_dir() {
    char dir[MAX_PATH]{};
    GetModuleFileNameA(g_module, dir, MAX_PATH);
    if (char* slash = std::strrchr(dir, '\\')) *slash = '\0';
    return dir;
}

bool compile(const char* src, const char* name, std::vector<uint8_t>& out) {
    ID3DBlob* code = nullptr;
    ID3DBlob* err = nullptr;
    const HRESULT hr = D3DCompile(src, std::strlen(src), name, nullptr, nullptr, "main", "cs_5_0",
                                  D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &err);
    if (FAILED(hr)) {
        reshade::log::message(reshade::log::level::error,
                              err ? static_cast<const char*>(err->GetBufferPointer())
                                  : "OpenNR: shader compile failed");
        if (err) err->Release();
        return false;
    }
    out.assign(static_cast<const uint8_t*>(code->GetBufferPointer()),
               static_cast<const uint8_t*>(code->GetBufferPointer()) + code->GetBufferSize());
    code->Release();
    if (err) err->Release();
    return true;
}

void Ctx::destroy() {
    if (!dev) return;
    // D3D11 keeps a resource alive while the GPU still uses it; D3D12 and Vulkan do not
    if (api != device_api::d3d11 && g_rt && g_rt->get_device() == dev)
        if (command_queue* q = g_rt->get_command_queue()) q->wait_idle();
    net.destroy(dev);
    resource_view* views[] = {&chans_uav, &chans_srv, &head_uav, &head_srv,
                              &A_uav, &A_srv, &B_uav, &B_srv, &scratch_uav,
                              &gbias_srv, &gbias_uav};
    for (resource_view* v : views) opennr::destroy_view(dev, *v);
    for (int i = 0; i < 8; ++i) {
        opennr::destroy_view(dev, skip_uav[i]);
        opennr::destroy_view(dev, skip_srv[i]);
        if (skip[i].handle) { forget(skip[i]); dev->destroy_resource(skip[i]); skip[i] = {}; }
    }
    if (src_copy_srv.handle) { dev->destroy_resource_view(src_copy_srv); src_copy_srv = {}; }
    for (resource* r : {&chans, &head, &A, &B, &scratch, &src_copy, &gbias})
        if (r->handle) { forget(*r); dev->destroy_resource(*r); *r = {}; }
    for (pipeline* p : {&stage_pso, &comp_pso, &conv_pso, &pool_pso, &upcat_pso, &glob_pso})
        if (p->handle) { dev->destroy_pipeline(*p); *p = {}; }
    for (pipeline_layout* l : {&layout_stage, &layout_comp})
        if (l->handle && l->handle != layout.handle) dev->destroy_pipeline_layout(*l);
    layout_stage = layout_comp = {};
    if (layout.handle) { dev->destroy_pipeline_layout(layout); layout = {}; }
    if (timer.handle) { dev->destroy_query_heap(timer); timer = {}; }
    slot = 0;
    for (bool& u : slot_used) u = false;
    gpu_ms = 0.0;
    ready = false;
    for (resource& r : up)
        if (r.handle) { dev->destroy_resource(r); r = {}; }
    up_size = 0;
}

bool Ctx::build(device* d, uint32_t OW, uint32_t OH, format target_fmt) {
    destroy();
    dev = d;
    ow = OW;
    oh = OH;
    fmt = target_fmt;
    // The network runs at up to 704 lines, keeping the output's aspect, and its correction is
    // upscaled to the output; the frame it is added to stays at full resolution.
    h = align_extent(std::min<uint32_t>(704, OH));
    w = align_extent(std::min<uint32_t>(uint32_t(double(h) * OW / OH + 0.5), OW));

    // recorded first, so a refusal is remembered rather than retried every frame
    model = g_model_idx;
    api = d->get_api();
    if (api == device_api::vulkan && !opennr::spirv::kHave) {
        reshade::log::message(reshade::log::level::error,
                              "OpenNR: this build has no Vulkan shaders -- frames pass through");
        return false;
    }
    if (api != device_api::d3d11 && api != device_api::d3d12 && api != device_api::vulkan) {
        reshade::log::message(reshade::log::level::error,
                              "OpenNR: only D3D11, D3D12 and Vulkan are supported -- frames pass "
                              "through");
        return false;
    }
    if (!d->check_capability(device_caps::compute_shader)) {
        reshade::log::message(reshade::log::level::error, "OpenNR: no compute shader support");
        return false;
    }

    std::string err;
    const std::string wdir = module_dir() + "\\" + kModelDirs[g_model_idx];
    if (!net.load(d, wdir, err)) {
        reshade::log::message(reshade::log::level::error, ("OpenNR: " + err).c_str());
        return false;
    }

    // t0, t1, t2, u0 -- one descriptor table each (a descriptor set each on Vulkan), then 12
    // push constants
    auto make_layout = [&](const descriptor_type (&types)[4], pipeline_layout* out) {
        descriptor_range ranges[4] = {};
        pipeline_layout_param params[5] = {};
        for (uint32_t i = 0; i < 4; ++i) {
            ranges[i] = {0, i == 3 ? 0u : i, 0, 1, shader_stage::compute, 1, types[i]};
            params[i].type = pipeline_layout_param_type::descriptor_table;
            params[i].descriptor_table.count = 1;
            params[i].descriptor_table.ranges = &ranges[i];
        }
        params[4].type = pipeline_layout_param_type::push_constants;
        params[4].push_constants = {0, 0, 0, 12, shader_stage::compute};
        return d->create_pipeline_layout(5, params, out);
    };
    constexpr descriptor_type SRV = descriptor_type::shader_resource_view;
    constexpr descriptor_type UAV = descriptor_type::unordered_access_view;
    constexpr descriptor_type SSB = descriptor_type::shader_storage_buffer;
    bool made = false;
    if (api != device_api::vulkan) {
        made = make_layout({SRV, SRV, SRV, UAV}, &layout);
        layout_stage = layout_comp = layout;
    } else {
        made = make_layout({SSB, SSB, SSB, SSB}, &layout) &&
               make_layout({SRV, SSB, SSB, SSB}, &layout_stage) &&   // frame -> channels
               make_layout({SRV, SSB, SRV, UAV}, &layout_comp);      // frame, output -> scratch
    }
    if (!made) {
        reshade::log::message(reshade::log::level::error, "OpenNR: create_pipeline_layout failed");
        return false;
    }

    struct Job { const char* src; const char* name; const char* spv; pipeline* out;
                 pipeline_layout lay; };
    const Job jobs[] = {{opennr::kStageHLSL, "stage", "kStageHLSL", &stage_pso, layout_stage},
                        {opennr::kCompositeHLSL, "composite", "kCompositeHLSL", &comp_pso,
                         layout_comp},
                        {opennr::kConvHLSL, "conv", "kConvHLSL", &conv_pso, layout},
                        {opennr::kPoolHLSL, "pool", "kPoolHLSL", &pool_pso, layout},
                        {opennr::kUpCatHLSL, "upcat", "kUpCatHLSL", &upcat_pso, layout},
                        {opennr::kGlobalHLSL, "global", "kGlobalHLSL", &glob_pso, layout}};
    for (const Job& j : jobs) {
        std::vector<uint8_t> dxbc;
        shader_desc sd{};
        sd.entry_point = "main";
        if (api == device_api::vulkan) {
            const opennr::spirv::Blob* b = opennr::spirv::find(j.spv);
            if (!b) {
                reshade::log::message(reshade::log::level::error,
                                      ("OpenNR: no Vulkan shader for " + std::string(j.name)).c_str());
                return false;
            }
            sd.code = b->code;
            sd.code_size = b->size;
        } else {
            if (!compile(j.src, j.name, dxbc)) return false;
            sd.code = dxbc.data();
            sd.code_size = dxbc.size();
        }
        const pipeline_subobject sub{pipeline_subobject_type::compute_shader, 1, &sd};
        if (!d->create_pipeline(j.lay, 1, &sub, j.out)) {
            reshade::log::message(reshade::log::level::error,
                                  ("OpenNR: create_pipeline failed for " + std::string(j.name))
                                      .c_str());
            return false;
        }
    }

    const uint64_t npix = uint64_t(w) * h;
    const uint64_t big = net.scratch_floats(w, h);
    uint64_t bytes = 0;
    auto buf = [&](uint64_t n, resource* r, resource_view* srv, resource_view* uav) {
        bytes += n * 2;                          // fp16, four channels to an element
        return opennr::Network::buffer(d, n / 4, 8, nullptr, r, srv, uav);
    };
    if (!buf(npix * 16, &chans, &chans_srv, &chans_uav) ||
        !buf(npix * net.convs.back().pad, &head, &head_srv, &head_uav) ||
        !buf(big, &A, &A_srv, &A_uav) || !buf(big, &B, &B_srv, &B_uav)) {
        reshade::log::message(reshade::log::level::error, "OpenNR: buffer allocation failed");
        return false;
    }
    for (resource r : {chans, head, A, B}) track(r, resource_usage::unordered_access);
    for (uint32_t i = 0; i < net.levels; ++i) {
        const uint64_t n = uint64_t(w >> i) * (h >> i) * (net.base << i);
        if (!buf(n, &skip[i], &skip_srv[i], &skip_uav[i])) {
            reshade::log::message(reshade::log::level::error, "OpenNR: buffer allocation failed");
            return false;
        }
        track(skip[i], resource_usage::unordered_access);
    }
    // the whole-frame branch pools 8x8 and then 2x2 twice, so the extent has to divide by 32
    if (net.glob) {
        const uint32_t lv = net.gconvs.back().level;
        if ((w >> lv) << lv != w || (h >> lv) << lv != h ||
            !opennr::Network::buffer(d, net.g_out / 4, 16, nullptr, &gbias, &gbias_srv,
                                     &gbias_uav)) {
            reshade::log::message(reshade::log::level::error,
                                  "OpenNR: the model does not fit this resolution");
            return false;
        }
        track(gbias, resource_usage::unordered_access);
    }
    // The finished frame is written to a texture of our own and copied onto the back buffer. On
    // D3D that texture has the back buffer's format, which the copy requires. On Vulkan it is
    // rgba16f, a format every device can store to from a shader, and ReShade's copy between the
    // two formats becomes a blit that converts.
    const format scratch_fmt = api == device_api::vulkan ? format::r16g16b16a16_float : target_fmt;
    if (!d->create_resource(resource_desc(OW, OH, 1, 1, scratch_fmt, 1, memory_heap::gpu_only,
                                          resource_usage::unordered_access |
                                              resource_usage::copy_source),
                            nullptr, resource_usage::unordered_access, &scratch) ||
        !d->create_resource_view(scratch, resource_usage::unordered_access,
                                 resource_view_desc(scratch_fmt), &scratch_uav)) {
        char e[160];
        std::snprintf(e, sizeof e,
                      "OpenNR: the output texture failed for back buffer format %u -- it may "
                      "not support shader writes", uint32_t(target_fmt));
        reshade::log::message(reshade::log::level::error, e);
        return false;
    }
    track(scratch, resource_usage::unordered_access);

    // optional: without timestamps the add-on still runs, it just cannot report its GPU time
    if (!d->create_query_heap(query_type::timestamp, RING * 2, &timer)) timer = {};

    // The frame is copied before anything reads it: the back buffer is still bound as a render
    // target here, and D3D11 will not also bind it for reading (the read would return black).
    if (!d->create_resource(resource_desc(OW, OH, 1, 1, target_fmt, 1, memory_heap::gpu_only,
                                          resource_usage::shader_resource |
                                              resource_usage::copy_dest),
                            nullptr, resource_usage::shader_resource, &src_copy) ||
        !d->create_resource_view(src_copy, resource_usage::shader_resource,
                                 resource_view_desc(target_fmt), &src_copy_srv)) {
        reshade::log::message(reshade::log::level::error, "OpenNR: frame copy allocation failed");
        return false;
    }
    track(src_copy, resource_usage::shader_resource);

    char msg[200];
    std::snprintf(msg, sizeof msg,
                  "OpenNR %s: %s, network %ux%u upscaled to %ux%u, %.0f MB, back buffer format %u",
                  kVersion, kModelLabels[g_model_idx], w, h, OW, OH, double(bytes) / 1e6,
                  uint32_t(target_fmt));
    reshade::log::message(reshade::log::level::info, msg);
    ready = true;
    return true;
}

// ------------------------------------------------------------------ the depth buffer, reported
//
// OpenNR does not use the depth buffer for the picture. What the overlay reports is what ReShade's
// Generic Depth add-on has picked, and whether that can be this frame's scene depth: a shadow map
// or a mirror is a different size or aspect from the frame, and is reported as rejected.
char g_depth_note[128] = "not looked for yet";

bool depth_fits(uint32_t dw, uint32_t dh, uint32_t OW, uint32_t OH) {
    if (dw == 0 || dh == 0 || OW == 0 || OH == 0) return false;
    const float a = float(dw) / float(dh), b = float(OW) / float(OH);
    if (a < b * 0.98f || a > b * 1.02f) return false;          // not the frame's aspect
    return dw * 2 >= OW && dw <= OW * 2;                       // half to double the frame's size
}

void update_depth_note(effect_runtime* rt, uint32_t OW, uint32_t OH) {
    // Generic Depth publishes the depth to effects that declare a DEPTH texture; resolved fresh
    // every frame, because its pick can change at any time and the old view is then destroyed.
    char note[128];
    uint32_t dw = 0, dh = 0;
    const effect_texture_variable v = rt->find_texture_variable(nullptr, "DepthBufferTex");
    resource_view srv{}, srv_srgb{};
    if (v.handle != 0) rt->get_texture_binding(v, &srv, &srv_srgb);
    if (v.handle == 0) {
        std::snprintf(note, sizeof note, "%s", "not available (no active ReShade effect reads depth)");
    } else if (srv.handle == 0) {
        std::snprintf(note, sizeof note, "%s", "not found yet");
    } else {
        const resource_desc rd = rt->get_device()->get_resource_desc(
            rt->get_device()->get_resource_from_view(srv));
        dw = rd.texture.width;
        dh = rd.texture.height;
        std::snprintf(note, sizeof note, "%ux%u, %s", dw, dh,
                      depth_fits(dw, dh, OW, OH) ? "matches the frame"
                                                 : "REJECTED, not this frame's scene depth");
    }
    if (std::strcmp(note, g_depth_note) != 0) {
        std::snprintf(g_depth_note, sizeof g_depth_note, "%s", note);
        reshade::log::message(reshade::log::level::info,
                              (std::string("OpenNR: depth buffer ") + note).c_str());
    }
}

void on_begin_effects(effect_runtime* rt, command_list*, resource_view, resource_view) {
    g_rt = rt;                            // for render_before_interface
    uint32_t OW = 0, OH = 0;
    rt->get_screenshot_width_and_height(&OW, &OH);
    update_depth_note(rt, OW, OH);
}

// ======================================================= the network on a GPU the player picks
//
// On the game's GPU the network adds to every frame's GPU time. A second GPU takes that work off
// the game's: the frame goes to the CPU, to the other GPU, through the network, and its
// correction comes back. Each hop is issued one frame and collected the next, so the correction
// for frame n arrives at frame n + 2 -- and the add-on keeps frame n itself as well, so what is
// shown is frame n, corrected, two frames late.
char g_net_gpu[128] = "";          // the adapter's name; empty is the game's own GPU
int g_net_gpu_idx = -1;            // its DXGI index, resolved against the game's device
bool g_net_gpu_pending = false;    // the name was read from the config and not resolved yet
void resolve_net_gpu(device* d);   // beside read_config, below
char g_remote_note[200] = "off";

struct AdapterInfo {
    int index;
    std::string name;
    LUID luid;
    bool software;
};

std::vector<AdapterInfo> list_adapters() {
    std::vector<AdapterInfo> out;
    IDXGIFactory1* fac = nullptr;
    if (FAILED(CreateDXGIFactory1(__uuidof(IDXGIFactory1), (void**)&fac))) return out;
    IDXGIAdapter1* ad = nullptr;
    for (UINT i = 0; fac->EnumAdapters1(i, &ad) != DXGI_ERROR_NOT_FOUND; ++i) {
        DXGI_ADAPTER_DESC1 d{};
        ad->GetDesc1(&d);
        char nm[128]{};
        WideCharToMultiByte(CP_UTF8, 0, d.Description, -1, nm, sizeof nm - 1, nullptr, nullptr);
        out.push_back({int(i), nm, d.AdapterLuid, (d.Flags & DXGI_ADAPTER_FLAG_SOFTWARE) != 0});
        ad->Release();
    }
    fac->Release();
    return out;
}

// the LUID of the adapter the game's device lives on (D3D11 and D3D12)
bool game_luid(device* d, LUID* out) {
    if (d->get_api() == device_api::d3d12) {
        auto* d12 = reinterpret_cast<ID3D12Device*>(d->get_native());
        if (!d12) return false;
        *out = d12->GetAdapterLuid();
        return true;
    }
    if (d->get_api() != device_api::d3d11) return false;
    auto* dev = reinterpret_cast<ID3D11Device*>(d->get_native());
    IDXGIDevice* dx = nullptr;
    if (!dev || FAILED(dev->QueryInterface(__uuidof(IDXGIDevice), (void**)&dx))) return false;
    IDXGIAdapter* ad = nullptr;
    const bool ok = SUCCEEDED(dx->GetAdapter(&ad));
    if (ok) {
        DXGI_ADAPTER_DESC desc{};
        ad->GetDesc(&desc);
        *out = desc.AdapterLuid;
        ad->Release();
    }
    dx->Release();
    return ok;
}

bool same_luid(LUID a, LUID b) { return a.LowPart == b.LowPart && a.HighPart == b.HighPart; }

struct Remote {
    static constexpr uint32_t R = 3;
    // what the device and buffers were built for; any change rebuilds
    int adapter = -1;
    uint32_t model = 0xffffffffu, w = 0, h = 0, ow = 0, oh = 0;
    format fmt = format::unknown;
    std::string name;
    bool ok = false, tried = false;

    // on the other GPU
    opennr::d3d::Net net;
    ID3D11Texture2D* src = nullptr;          // the frame, uploaded from the CPU
    ID3D11ShaderResourceView* src_srv = nullptr;
    ID3D11Buffer* rb[R] = {};                // the packed output, on its way back to the CPU
    bool pending[R] = {};

    // on the game's GPU
    resource gstage[R] = {};                 // the frame, on its way to the CPU
    resource frame[R] = {};                  // the frame, kept until its correction comes back
    resource_view frame_srv[R] = {};
    resource head = {};                      // the packed output, one uint2 a pixel
    resource_view head_srv = {};
    uint64_t n = 0;
    // D3D12: a slot's readback copy is mapped only once this fence says it has landed
    device_api api = device_api::d3d11;
    fence fnc = {};
    uint64_t fval = 0, fv[R] = {};
    int unsignaled = -1;
    double feed_ms = 0.0, wait_ms = 0.0;

    void destroy(device* d) {
        if (api != device_api::d3d11 && (fnc.handle || gstage[0].handle) && g_rt &&
            g_rt->get_device() == d)
            if (command_queue* q = g_rt->get_command_queue()) q->wait_idle();
        if (fnc.handle) { d->destroy_fence(fnc); fnc = {}; }
        fval = 0;
        unsignaled = -1;
        for (uint32_t k = 0; k < R; ++k) {
            fv[k] = 0;
            if (rb[k]) { rb[k]->Release(); rb[k] = nullptr; }
            pending[k] = false;
            if (frame_srv[k].handle) { d->destroy_resource_view(frame_srv[k]); frame_srv[k] = {}; }
            for (resource* r : {&gstage[k], &frame[k]})
                if (r->handle) { g.forget(*r); d->destroy_resource(*r); *r = {}; }
        }
        if (head_srv.handle) { d->destroy_resource_view(head_srv); head_srv = {}; }
        if (head.handle) { g.forget(head); d->destroy_resource(head); head = {}; }
        if (src_srv) { src_srv->Release(); src_srv = nullptr; }
        if (src) { src->Release(); src = nullptr; }
        net.release();
        if (net.ctx) { net.ctx->Release(); net.ctx = nullptr; }
        if (net.dev) { net.dev->Release(); net.dev = nullptr; }
        n = 0;
        ok = false;
    }

    bool fail(const std::string& why) {
        std::snprintf(g_remote_note, sizeof g_remote_note, "%.190s", why.c_str());
        reshade::log::message(reshade::log::level::error, ("OpenNR: " + why).c_str());
        return false;
    }

    bool build(device* d, int idx, uint32_t W, uint32_t H, uint32_t OW, uint32_t OH, format f,
               const std::string& wdir) {
        destroy(d);
        adapter = idx; model = g_model_idx;
        w = W; h = H; ow = OW; oh = OH; fmt = f;
        tried = true;
        api = d->get_api();
        if (api == device_api::d3d12 && !d->create_fence(0, fence_flags::none, &fnc))
            return fail("no fence for the readbacks");

        IDXGIFactory1* fac = nullptr;
        IDXGIAdapter1* ad = nullptr;
        if (FAILED(CreateDXGIFactory1(__uuidof(IDXGIFactory1), (void**)&fac)) ||
            fac->EnumAdapters1(UINT(idx), &ad) != S_OK) {
            if (fac) fac->Release();
            return fail("the chosen GPU is not there any more");
        }
        DXGI_ADAPTER_DESC1 desc{};
        ad->GetDesc1(&desc);
        char nm[128]{};
        WideCharToMultiByte(CP_UTF8, 0, desc.Description, -1, nm, sizeof nm - 1, nullptr, nullptr);
        name = nm;
        const HRESULT hr = D3D11CreateDevice(ad, D3D_DRIVER_TYPE_UNKNOWN, nullptr, 0, nullptr, 0,
                                             D3D11_SDK_VERSION, &net.dev, nullptr, &net.ctx);
        ad->Release();
        fac->Release();
        if (FAILED(hr)) return fail("could not start on " + name);
        if (!net.load(wdir) || !net.alloc(W, H)) return fail(name + ": " + net.err);

        // the frame on the other GPU, in the back buffer's own format
        D3D11_TEXTURE2D_DESC td{};
        td.Width = OW; td.Height = OH; td.MipLevels = 1; td.ArraySize = 1;
        td.Format = DXGI_FORMAT(uint32_t(format_to_default_typed(f)));
        td.SampleDesc.Count = 1;
        td.Usage = D3D11_USAGE_DEFAULT;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        if (FAILED(net.dev->CreateTexture2D(&td, nullptr, &src)) ||
            FAILED(net.dev->CreateShaderResourceView(src, nullptr, &src_srv)))
            return fail(name + ": this frame format is not supported (" +
                        std::to_string(uint32_t(f)) + ")");
        D3D11_BUFFER_DESC bd{};
        bd.ByteWidth = W * H * 8;
        bd.Usage = D3D11_USAGE_STAGING;
        bd.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
        for (uint32_t k = 0; k < R; ++k)
            if (FAILED(net.dev->CreateBuffer(&bd, nullptr, &rb[k])))
                return fail(name + ": readback buffers failed");

        // and on the game's
        for (uint32_t k = 0; k < R; ++k) {
            if (!d->create_resource(resource_desc(OW, OH, 1, 1, f, 1, memory_heap::gpu_to_cpu,
                                                  resource_usage::copy_dest),
                                    nullptr, resource_usage::copy_dest, &gstage[k]))
                return fail("the frame's readback copy failed");
            if (!d->create_resource(resource_desc(OW, OH, 1, 1, f, 1, memory_heap::gpu_only,
                                                  resource_usage::shader_resource |
                                                      resource_usage::copy_dest),
                                    nullptr, resource_usage::shader_resource, &frame[k]) ||
                !d->create_resource_view(frame[k], resource_usage::shader_resource,
                                         resource_view_desc(format_to_default_typed(f)),
                                         &frame_srv[k]))
                return fail("the delayed-frame copies failed");
        }
        const uint64_t np = uint64_t(W) * H;
        resource_desc rd(np * 8, memory_heap::gpu_only,
                         resource_usage::shader_resource | resource_usage::copy_dest);
        rd.buffer.structured.stride = 8;
        resource_view_desc vd{};
        vd.type = resource_view_type::buffer;
        vd.format = format::unknown;
        vd.buffer.offset = 0;
        vd.buffer.structured.count = uint32_t(np);
        vd.buffer.structured.stride = 8;
        if (!d->create_resource(rd, nullptr, resource_usage::shader_resource, &head) ||
            !d->create_resource_view(head, resource_usage::shader_resource, vd, &head_srv))
            return fail("the output buffer failed");
        for (uint32_t k = 0; k < R; ++k) {
            g.track(gstage[k], resource_usage::copy_dest);
            g.track(frame[k], resource_usage::shader_resource);
        }
        g.track(head, resource_usage::shader_resource);
        ok = true;
        std::snprintf(g_remote_note, sizeof g_remote_note, "starting on %.150s", name.c_str());
        return true;
    }

    // One frame of the pipeline. Returns the ring slot whose correction just arrived -- the frame
    // to composite and show now -- or -1 while the pipeline is still filling.
    int step(device* d, command_list* cmd, resource frame_src, const uint32_t (&stage_args)[12],
             uint32_t head_group) {
        const uint32_t cur = uint32_t(n % R);
        // (a) this frame: what the network will read, and the frame it will be shown on
        g.use(cmd, frame_src, resource_usage::copy_source);
        for (resource r : {gstage[cur], frame[cur]}) g.use(cmd, r, resource_usage::copy_dest);
        cmd->copy_texture_region(frame_src, 0, nullptr, gstage[cur], 0, nullptr);
        cmd->copy_texture_region(frame_src, 0, nullptr, frame[cur], 0, nullptr);
        if (api == device_api::d3d12) { fv[cur] = 0; unsignaled = int(cur); }

        // (b) last frame, to the other GPU, which then runs while this one gets on with the game
        LARGE_INTEGER q0, q1, q2, qf;
        QueryPerformanceFrequency(&qf);
        QueryPerformanceCounter(&q0);
        if (n >= 1) {
            const uint32_t k = uint32_t((n - 1) % R);
            subresource_data m{};
            const bool landed = api != device_api::d3d12 ||
                                (fv[k] != 0 && d->wait(fnc, fv[k], 1000000000ull));
            if (landed && d->map_texture_region(gstage[k], 0, nullptr, map_access::read_only, &m)) {
                net.ctx->UpdateSubresource(src, 0, nullptr, m.data, m.row_pitch, 0);
                d->unmap_texture_region(gstage[k], 0);
                UINT sa[12] = {};
                for (int i = 0; i < 12; ++i) sa[i] = stage_args[i];
                net.stage(src_srv, sa);
                net.run();
                net.pack(head_group);
                net.ctx->CopyResource(rb[k], net.packed.res);
                net.ctx->Flush();
                pending[k] = true;
            }
        }
        QueryPerformanceCounter(&q1);

        // (c) the correction for two frames ago, back to this GPU. The game waits here when the
        // other GPU is slower than two of its frames.
        int ready = -1;
        if (n >= 2) {
            const uint32_t k2 = uint32_t((n - 2) % R);
            D3D11_MAPPED_SUBRESOURCE m{};
            if (pending[k2] && SUCCEEDED(net.ctx->Map(rb[k2], 0, D3D11_MAP_READ, 0, &m))) {
                g.upload(d, cmd, m.pData, uint64_t(w) * h * 8, head);
                net.ctx->Unmap(rb[k2], 0);
                pending[k2] = false;
                ready = int(k2);
            }
        }
        QueryPerformanceCounter(&q2);
        const double f1 = double(q1.QuadPart - q0.QuadPart) * 1000.0 / double(qf.QuadPart);
        const double f2 = double(q2.QuadPart - q1.QuadPart) * 1000.0 / double(qf.QuadPart);
        feed_ms = feed_ms == 0.0 ? f1 : feed_ms * 0.9 + f1 * 0.1;
        wait_ms = wait_ms == 0.0 ? f2 : wait_ms * 0.9 + f2 * 0.1;
        std::snprintf(g_remote_note, sizeof g_remote_note,
                      "running on %.100s, shown 2 frames late (CPU: send %.1f ms, wait %.1f ms)",
                      name.c_str(), feed_ms, wait_ms);
        ++n;
        return ready;
    }
};
Remote g_remote;
// Guards the frame's work: on D3D12 the correction can run on a game recording thread while the
// presenting thread is in ReShade's present-time pass.
std::mutex g_frame_mutex;

void signal_remote_copy(command_queue* q, bool flush) {
    Remote& r = g_remote;
    if (!q || !r.ok || r.unsignaled < 0 || !r.fnc.handle) return;
    if (flush) q->flush_immediate_command_list();
    q->signal(r.fnc, ++r.fval);
    r.fv[r.unsignaled] = r.fval;
    r.unsignaled = -1;
}

// ================================================================= correcting before the HUD
//
// Many games draw the 3D scene into a texture of their own, copy it to the screen with one
// full-screen draw, and then draw the HUD with indexed draws on top. The first indexed draw into
// the back buffer after such a full-screen draw is where the HUD starts, and the add-on corrects
// the frame right there: the game then draws its HUD over the corrected picture. A frame without
// that pattern is corrected at present, HUD included.
//
// D3D11: ReShade is asked to render its effects at that point (`render_effects`), which also
// moves other ReShade effects before the HUD. The game's whole context state is set aside with
// SwapDeviceContextState around it and put back after.
//
// D3D12: the work is recorded straight into the game's command list, and what it disturbs is put
// back -- the pipeline state, the compute root signature and its arguments, and the descriptor
// heaps. ReShade still runs its present-time pass for its own effects; the add-on's part of it
// stands down for a frame whose list carried the correction.
//
// Vulkan: always at present.

// Which buffers are the swap chain's, refreshed at every present. Read from several recording
// threads on D3D12, hence atomics.
std::atomic<uint64_t> g_bb[8] = {};
std::atomic<uint32_t> g_bb_count{0};
std::atomic<uint32_t> g_bb_w{0}, g_bb_h{0};
std::atomic<bool> g_d3d12{false};

bool is_back_buffer(uint64_t h) {
    if (!h) return false;
    const uint32_t n = std::min<uint32_t>(g_bb_count.load(std::memory_order_acquire), 8);
    for (uint32_t i = 0; i < n; ++i)
        if (g_bb[i].load(std::memory_order_relaxed) == h) return true;
    return false;
}

// What is known about one command list: where the HUD starts in it, and on D3D12 the bindings
// the correction disturbs. D3D12 games record several lists at once, so this lives on each list.
struct RootArgs {
    pipeline_layout layout = {};
    std::vector<std::pair<uint32_t, descriptor_table>> tables;        // parameter, table
    std::vector<std::pair<uint32_t, std::vector<uint32_t>>> consts;   // parameter, values from 0
    std::vector<std::pair<uint32_t, buffer_range>> cbvs;              // parameter, root CBV
    // a new root signature drops every argument set under the old one
    void set_layout(pipeline_layout l) {
        if (l.handle == layout.handle) return;
        layout = l;
        tables.clear();
        consts.clear();
        cbvs.clear();
    }
    template <typename T> static void put(std::vector<std::pair<uint32_t, T>>& v, uint32_t p, const T& x) {
        for (auto& e : v) if (e.first == p) { e.second = x; return; }
        v.push_back({p, x});
    }
};
struct __declspec(uuid("7c2d0e41-5b3a-4f28-9a61-0d4e8b9c2f35")) ListState {
    uint64_t rt = 0, rtv = 0;             // the first render target, and the view it is bound through
    bool bb = false, ds = false;          // ... is it a swap-chain buffer; is a depth bound
    bool in_pass = false;                 // inside a D3D12 render pass, where nothing can be inserted
    float vw = 0, vh = 0;
    bool comp_seen = false;               // a full-screen draw into the back buffer, in this list
    bool corrected = false;               // this list carries the correction
    pipeline_stage pso_stages = pipeline_stage::all_graphics;
    pipeline pso = {};
    RootArgs gfx, cs;
};
ListState* list_state(command_list* cmd) {
    ListState* s = cmd->get_private_data<ListState>();
    return s ? s : cmd->create_private_data<ListState>();
}

uint32_t g_preui = 1;                     // on unless switched off
const char* g_preui_note = "off";         // what the last frame did, for the overlay
std::atomic<const char*> g_preui_why{nullptr};   // why this frame could not, when it could not
std::atomic<bool> g_comp_seen{false};     // a full-screen draw into the back buffer, this frame
std::atomic<bool> g_preui_tried{false};   // the first HUD draw has been reached, this frame
std::atomic<bool> g_preui_done{false};    // ... and the correction ran there
std::atomic<int> g_preui_exec{0};         // D3D12: corrected lists the game has submitted
thread_local bool g_in_preui = false;     // on_finish_effects is running inside that call
ID3DDeviceContextState* g_blank_state = nullptr;
ID3D11Device* g_blank_dev = nullptr;

void release_blank_state() {
    if (g_blank_state) g_blank_state->Release();
    g_blank_state = nullptr;
    g_blank_dev = nullptr;
}

// D3D11. False, having changed nothing, when anything it needs is missing; the frame is then
// corrected at present as usual.
bool render_before_interface(command_list* cmd, const ListState& s) {
    effect_runtime* const rt = g_rt;
    if (!rt || rt->get_device() != cmd->get_device()) {
        g_preui_why = "ReShade is not ready yet";
        return false;
    }
    // SwapDeviceContextState exists on the immediate context only
    command_queue* const q = rt->get_command_queue();
    if (!q || q->get_immediate_command_list() != cmd) {
        g_preui_why = "this game draws its HUD on another thread";
        return false;
    }
    device* const d = cmd->get_device();
    auto* const dev = reinterpret_cast<ID3D11Device*>(d->get_native());
    auto* const ctx = reinterpret_cast<ID3D11DeviceContext*>(cmd->get_native());
    if (!dev || !ctx) {
        g_preui_why = "no D3D11 device";
        return false;
    }
    ID3D11DeviceContext1* ctx1 = nullptr;
    if (FAILED(ctx->QueryInterface(__uuidof(ID3D11DeviceContext1), (void**)&ctx1))) {
        g_preui_why = "D3D11.1 is not available on this system";
        return false;
    }
    if (g_blank_dev != dev) {
        release_blank_state();
        ID3D11Device1* dev1 = nullptr;
        if (SUCCEEDED(dev->QueryInterface(__uuidof(ID3D11Device1), (void**)&dev1))) {
            const D3D_FEATURE_LEVEL fl = dev->GetFeatureLevel();
            // a single-threaded device takes only a single-threaded state object
            const UINT flags = (dev->GetCreationFlags() & D3D11_CREATE_DEVICE_SINGLETHREADED)
                                   ? D3D11_1_CREATE_DEVICE_CONTEXT_STATE_SINGLETHREADED : 0;
            if (SUCCEEDED(dev1->CreateDeviceContextState(flags, &fl, 1, D3D11_SDK_VERSION,
                                                         __uuidof(ID3D11Device), nullptr,
                                                         &g_blank_state)))
                g_blank_dev = dev;
            dev1->Release();
        }
    }
    if (!g_blank_state) {
        ctx1->Release();
        g_preui_why = "could not set the game's state aside";
        return false;
    }
    // Views of the back buffer for ReShade's own passes, plain and sRGB, made for this call and
    // dropped after it (a view kept across frames would hold the buffer through a resize).
    const resource bb{s.rt};
    const format f = d->get_resource_desc(bb).texture.format;
    resource_view rtv{}, rtv_srgb{};
    d->create_resource_view(bb, resource_usage::render_target,
                            resource_view_desc(format_to_default_typed(f, 0)), &rtv);
    d->create_resource_view(bb, resource_usage::render_target,
                            resource_view_desc(format_to_default_typed(f, 1)), &rtv_srgb);
    const resource_view plain = rtv.handle ? rtv : resource_view{s.rtv};

    ID3DDeviceContextState* game = nullptr;
    ctx1->SwapDeviceContextState(g_blank_state, &game);
    g_in_preui = true;
    rt->render_effects(cmd, plain, rtv_srgb.handle ? rtv_srgb : plain);
    g_in_preui = false;
    ctx1->ClearState();                   // the stand-in state keeps no reference to the frame
    ctx1->SwapDeviceContextState(game, nullptr);
    if (game) game->Release();
    ctx1->Release();
    if (rtv.handle) d->destroy_resource_view(rtv);
    if (rtv_srgb.handle) d->destroy_resource_view(rtv_srgb);
    return true;
}

void on_finish_effects(effect_runtime* rt, command_list* cmd, resource_view rtv, resource_view);

// D3D12: put back what the correction's dispatches changed in the game's command list. Compute
// first, then the graphics tables (which also moves the descriptor heaps back to the game's),
// then the pipeline state.
void restore_d3d12(command_list* cmd, const ListState& s) {
    if (s.cs.layout.handle) {
        for (const auto& [p, t] : s.cs.tables)
            cmd->bind_descriptor_tables(shader_stage::all_compute, s.cs.layout, p, 1, &t);
        for (const auto& [p, v] : s.cs.consts)
            cmd->push_constants(shader_stage::all_compute, s.cs.layout, p, 0, uint32_t(v.size()),
                                v.data());
        for (const auto& [p, b] : s.cs.cbvs)
            cmd->push_descriptors(shader_stage::all_compute, s.cs.layout, p,
                                  descriptor_table_update{{}, 0, 0, 1,
                                                          descriptor_type::constant_buffer, &b});
    }
    for (const auto& [p, t] : s.gfx.tables)
        cmd->bind_descriptor_tables(shader_stage::all_graphics, s.gfx.layout, p, 1, &t);
    for (const auto& [p, v] : s.gfx.consts)
        cmd->push_constants(shader_stage::all_graphics, s.gfx.layout, p, 0, uint32_t(v.size()),
                            v.data());
    for (const auto& [p, b] : s.gfx.cbvs)
        cmd->push_descriptors(shader_stage::all_graphics, s.gfx.layout, p,
                              descriptor_table_update{{}, 0, 0, 1,
                                                      descriptor_type::constant_buffer, &b});
    cmd->bind_pipeline(s.pso_stages, s.pso);
}

bool correct_before_interface_d3d12(command_list* cmd, ListState& s) {
    effect_runtime* const rt = g_rt;
    if (!rt || rt->get_device() != cmd->get_device()) {
        g_preui_why = "ReShade is not ready yet";
        return false;
    }
    if (s.in_pass) {
        g_preui_why = "this game draws its HUD inside a render pass";
        return false;
    }
    // without the game's graphics tables there is no way back to its descriptor heaps
    if (!s.pso.handle || !s.gfx.layout.handle || s.gfx.tables.empty()) {
        g_preui_why = "the HUD's bindings were not seen";
        return false;
    }
    g_in_preui = true;
    on_finish_effects(rt, cmd, resource_view{s.rtv}, resource_view{s.rtv});
    g_in_preui = false;
    restore_d3d12(cmd, s);
    s.corrected = true;
    return true;
}

void on_present(command_queue* queue, swapchain* sc, const rect*, const rect*, uint32_t, const rect*) {
    // the swap chain's buffers, refreshed every frame -- a resize replaces them
    device* const dev = sc->get_device();
    g_d3d12 = dev->get_api() == device_api::d3d12;
    const uint32_t n = std::min<uint32_t>(sc->get_back_buffer_count(), 8);
    for (uint32_t i = 0; i < n; ++i) g_bb[i].store(sc->get_back_buffer(i).handle, std::memory_order_relaxed);
    g_bb_count.store(n, std::memory_order_release);
    if (n) {
        const resource_desc bd = dev->get_resource_desc(sc->get_back_buffer(0));
        g_bb_w = bd.texture.width;
        g_bb_h = bd.texture.height;
    }
    // A second-GPU copy recorded in a game list before the HUD: that list has been submitted by
    // now, on this queue, so a signal here lands after it.
    {
        std::lock_guard<std::mutex> lk(g_frame_mutex);
        signal_remote_copy(queue, false);
    }
    // what the frame now ending did, for the overlay, and each change of it in ReShade.log
    {
        const char* why = g_preui_why.load();
        const char* now = !g_preui       ? "off"
                          : g_preui_done ? "active: the HUD is drawn over the corrected picture"
                          : why          ? why
                          : g_comp_seen  ? "no HUD draw found after the scene in this frame"
                                         : "this scene does not have the pattern OpenNR looks for";
        if (now != g_preui_note) {
            g_preui_note = now;
            char msg[200];
            std::snprintf(msg, sizeof msg, "OpenNR: correcting before the HUD: %s", now);
            reshade::log::message(reshade::log::level::info, msg);
        }
    }
    g_comp_seen = false;
    g_preui_tried = false;
    g_preui_done = false;
    g_preui_why = nullptr;
    // D3D11's immediate context is never reset, so its per-frame mark is cleared here; a D3D12
    // list's goes with the list at its reset
    if (queue)
        if (command_list* imm = queue->get_immediate_command_list())
            if (ListState* s = imm->get_private_data<ListState>()) s->comp_seen = false;
}

// ---- the per-list tracking
void on_init_list(command_list* cmd) { cmd->create_private_data<ListState>(); }
void on_destroy_list(command_list* cmd) { cmd->destroy_private_data<ListState>(); }
void on_reset_list(command_list* cmd) {
    if (ListState* s = cmd->get_private_data<ListState>()) *s = ListState();
}
void on_execute_list(command_queue*, command_list* cmd) {
    if (ListState* s = cmd->get_private_data<ListState>())
        if (s->corrected) {
            s->corrected = false;
            ++g_preui_exec;
        }
}
bool on_begin_pass(command_list* cmd, uint32_t count, const render_pass_render_target_desc* rts,
                   const render_pass_depth_stencil_desc* ds, render_pass_flags) {
    if (!g_preui) return false;
    ListState* s = list_state(cmd);
    s->in_pass = true;
    s->rtv = count ? rts[0].view.handle : 0;
    s->rt = s->rtv ? cmd->get_device()->get_resource_from_view(rts[0].view).handle : 0;
    s->bb = is_back_buffer(s->rt);
    s->ds = ds && ds->view.handle != 0;
    return false;
}
bool on_end_pass(command_list* cmd) {
    if (ListState* s = cmd->get_private_data<ListState>()) s->in_pass = false;
    return false;
}
void on_bind_tables(command_list* cmd, shader_stage stages, pipeline_layout layout, uint32_t first,
                    uint32_t count, const descriptor_table* tables, uint32_t, const uint32_t*) {
    if (!g_preui || !g_d3d12) return;
    ListState* s = list_state(cmd);
    RootArgs& a = (stages & shader_stage::all_compute) != 0 ? s->cs : s->gfx;
    a.set_layout(layout);
    for (uint32_t i = 0; i < count; ++i) RootArgs::put(a.tables, first + i, tables[i]);
}
void on_push_consts(command_list* cmd, shader_stage stages, pipeline_layout layout, uint32_t param,
                    uint32_t first, uint32_t count, const void* values) {
    if (!g_preui || !g_d3d12) return;
    ListState* s = list_state(cmd);
    RootArgs& a = (stages & shader_stage::all_compute) != 0 ? s->cs : s->gfx;
    a.set_layout(layout);
    std::vector<uint32_t>* v = nullptr;
    for (auto& e : a.consts) if (e.first == param) v = &e.second;
    if (!v) { a.consts.push_back({param, {}}); v = &a.consts.back().second; }
    if (v->size() < first + count) v->resize(first + count);
    std::memcpy(v->data() + first, values, size_t(count) * 4);
}
void on_push_descs(command_list* cmd, shader_stage stages, pipeline_layout layout, uint32_t param,
                   const descriptor_table_update& u) {
    if (!g_preui || !g_d3d12) return;
    ListState* s = list_state(cmd);
    RootArgs& a = (stages & shader_stage::all_compute) != 0 ? s->cs : s->gfx;
    a.set_layout(layout);
    if (u.type == descriptor_type::constant_buffer && u.count == 1 && u.descriptors)
        RootArgs::put(a.cbvs, param, *static_cast<const buffer_range*>(u.descriptors));
}
void on_bind_rt(command_list* cmd, uint32_t count, const resource_view* rtvs, resource_view dsv) {
    if (!g_preui) return;
    device* const d = cmd->get_device();
    ListState* s = list_state(cmd);
    s->rtv = count ? rtvs[0].handle : 0;
    s->rt = s->rtv ? d->get_resource_from_view(rtvs[0]).handle : 0;
    s->bb = is_back_buffer(s->rt);
    s->ds = dsv.handle != 0;
}
void on_bind_vp(command_list* cmd, uint32_t first, uint32_t count, const viewport* vps) {
    if (first != 0 || count == 0 || !g_preui) return;
    ListState* s = list_state(cmd);
    s->vw = vps[0].width;
    s->vh = vps[0].height;
}
void on_bind_pipe(command_list* cmd, pipeline_stage stages, pipeline p) {
    if (!g_preui || !g_d3d12) return;
    // D3D12 has one pipeline-state slot, graphics or compute; the last one set is what goes back
    ListState* s = list_state(cmd);
    s->pso_stages = stages;
    s->pso = p;
}
bool on_draw(command_list* cmd, uint32_t v, uint32_t inst, uint32_t, uint32_t) {
    // the scene onto the back buffer: a full-screen triangle or quad, one instance, no depth
    // buffer, a viewport covering the whole buffer
    if (!g_preui || !g.ready) return false;
    ListState* s = list_state(cmd);
    if (s->bb && !s->ds && inst == 1 && v >= 3 && v <= 6 &&
        s->vw >= float(g_bb_w.load()) && s->vh >= float(g_bb_h.load())) {
        s->comp_seen = true;
        g_comp_seen = true;
    }
    return false;
}
bool on_draw_indexed(command_list* cmd, uint32_t, uint32_t, uint32_t, int32_t, uint32_t) {
    // the first HUD draw: correct the frame now, under it
    if (!g_preui || g_in_preui || !g.ready) return false;
    ListState* s = list_state(cmd);
    if (!s->comp_seen || !s->bb || s->ds) return false;
    s->comp_seen = false;                 // one attempt per full-screen draw
    if (g_preui_tried.exchange(true)) return false;   // and one a frame
    bool ok = false;
    if (g.api == device_api::d3d11)
        ok = render_before_interface(cmd, *s);
    else if (g.api == device_api::d3d12)
        ok = correct_before_interface_d3d12(cmd, *s);
    else
        g_preui_why = "not available on Vulkan yet";
    g_preui_done = ok;
    return false;
}

// ------------------------------------------------------------------------------ the frame
void finish_effects_locked(effect_runtime* rt, command_list* cmd, resource_view rtv);
void on_finish_effects(effect_runtime* rt, command_list* cmd, resource_view rtv, resource_view) {
    // a D3D12 frame corrected before its HUD: this is ReShade's present-time pass for its own
    // effects, and the add-on's part of it stands down
    if (!g_in_preui && g.api == device_api::d3d12 && g.ready && g_preui_exec.exchange(0) > 0)
        return;
    std::lock_guard<std::mutex> lk(g_frame_mutex);
    finish_effects_locked(rt, cmd, rtv);
}

void finish_effects_locked(effect_runtime* rt, command_list* cmd, resource_view rtv) {
    device* d = rt->get_device();
    uint32_t OW = 0, OH = 0;
    rt->get_screenshot_width_and_height(&OW, &OH);
    if (OW == 0 || OH == 0) return;

    const resource target = d->get_resource_from_view(rtv);
    const format target_fmt = d->get_resource_desc(target).texture.format;
    if (!g.ready || g.ow != OW || g.oh != OH || g.dev != d || g.fmt != target_fmt ||
        g.model != g_model_idx) {
        if (g.failed && g.ow == OW && g.oh == OH && g.dev == d && g.fmt == target_fmt &&
            g.model == g_model_idx)
            return;
        if (!g.build(d, OW, OH, target_fmt)) {
            g.failed = true;
            reshade::log::message(reshade::log::level::error,
                                  "OpenNR: setup failed, the frame passes through unchanged");
            return;
        }
        g.failed = false;
    }

    // The four slots and the 12 push constants of one dispatch. The UAV goes down FIRST: every
    // dispatch reads what the previous one wrote, and D3D11 drops an SRV whose resource is still
    // bound as the previous dispatch's UAV (the read would return zeros). An empty slot is pushed
    // on D3D11 only, where it unbinds what the last dispatch left there; elsewhere it is skipped,
    // and a kernel that leaves a slot empty does not declare it. On Vulkan a buffer's stand-in is
    // bound as a storage buffer.
    auto bind = [&](pipeline pso, const resource_view (&vs)[4], const uint32_t (&args)[12]) {
        const pipeline_layout lay = g.layout_for(pso);
        for (uint32_t n = 0; n < 4; ++n) {
            const uint32_t i = (n == 0) ? 3u : n - 1u;          // 3, 0, 1, 2 -- UAV first
            if (g.api != device_api::d3d11 && !vs[i].handle) continue;
            if (g.api == device_api::vulkan) {
                if (opennr::is_buffer_stand_in(vs[i])) {
                    buffer_range br{resource{vs[i].handle}, 0, UINT64_MAX};
                    cmd->push_descriptors(shader_stage::compute, lay, i,
                                          descriptor_table_update{
                                              {}, 0, 0, 1,
                                              descriptor_type::shader_storage_buffer, &br});
                    continue;
                }
            }
            const descriptor_table_update up{
                {}, 0, 0, 1,
                i == 3 ? descriptor_type::unordered_access_view
                       : descriptor_type::shader_resource_view,
                const_cast<resource_view*>(&vs[i])};
            cmd->push_descriptors(shader_stage::compute, lay, i, up);
        }
        cmd->push_constants(shader_stage::compute, lay, 4, 0, 12, args);
    };
    auto go = [&](pipeline pso, resource_view t0, resource_view t1, resource_view t2,
                  resource_view u0, const uint32_t (&args)[12], uint32_t groups) {
        g.use_view(cmd, u0, resource_usage::unordered_access);
        for (resource_view t : {t0, t1, t2}) g.use_view(cmd, t, resource_usage::shader_resource);
        cmd->bind_pipeline(pipeline_stage::compute_shader, pso);
        const resource_view vs[4] = {t0, t1, t2, u0};
        bind(pso, vs, args);
        cmd->dispatch(groups, 1, 1);
    };
    auto go2d = [&](pipeline pso, resource_view t0, resource_view t1, resource_view u0,
                    const uint32_t (&args)[12], uint32_t X, uint32_t Y) {
        g.use_view(cmd, u0, resource_usage::unordered_access);
        for (resource_view t : {t0, t1}) g.use_view(cmd, t, resource_usage::shader_resource);
        cmd->bind_pipeline(pipeline_stage::compute_shader, pso);
        const resource_view vs[4] = {t0, t1, {}, u0};
        bind(pso, vs, args);
        cmd->dispatch((X + 7) / 8, (Y + 7) / 8, 1);
    };

    // The slot about to be overwritten is RING frames old, so its result is ready without a
    // stall. Timestamps written into a game's own D3D12 list do not reliably come back, so a
    // frame corrected there is not timed rather than timed wrongly.
    const bool timed = g.timer.handle && !(g_in_preui && g.api != device_api::d3d11);
    g.untimed = !timed;
    if (timed && g.slot_used[g.slot]) {
        uint64_t t[2] = {};
        if (g.tick_hz == 0)
            if (command_queue* q = rt->get_command_queue()) g.tick_hz = q->get_timestamp_frequency();
        if (g.tick_hz != 0 &&
            d->get_query_heap_results(g.timer, query_type::timestamp, g.slot * 2, 2, t,
                                      sizeof(uint64_t)) &&
            t[1] > t[0]) {
            const double ms = double(t[1] - t[0]) * 1000.0 / double(g.tick_hz);
            g.gpu_ms = g.gpu_ms == 0.0 ? ms : g.gpu_ms * 0.9 + ms * 0.1;
        }
    }
    if (timed) cmd->end_query(g.timer, query_type::timestamp, g.slot * 2);

    // a readable copy of the frame, before anything reads it (see Ctx::build). The back buffer
    // is not ours and not tracked: it is a render target on either side of this.
    const resource_view src_srv = g.src_copy_srv;
    cmd->barrier(target, resource_usage::render_target, resource_usage::copy_source);
    g.use(cmd, g.src_copy, resource_usage::copy_dest);
    cmd->copy_texture_region(target, 0, nullptr, g.src_copy, 0, nullptr);
    cmd->barrier(target, resource_usage::copy_source, resource_usage::render_target);

    // The network on another GPU, when the player picked one. Built on first use and again
    // whenever what it was built for changes; a build that fails is not retried until something
    // changes, and the frame falls back to this GPU.
    if (g_net_gpu_pending) resolve_net_gpu(d);
    bool remote_now = false;
    int remote_slot = -1;
    const bool remote_api = g.api == device_api::d3d11 || g.api == device_api::d3d12;
    // the output group for Model A/B/C, when the model has one output per model
    const uint32_t group = g.net.cout >= 12 ? (g_model < 2u ? g_model : 2u) : 0u;
    if (g_net_gpu_idx >= 0 && remote_api) {
        Remote& r = g_remote;
        const bool stale = r.adapter != g_net_gpu_idx || r.model != g_model_idx || r.w != g.w ||
                           r.h != g.h || r.ow != OW || r.oh != OH || r.fmt != target_fmt;
        if (stale || (!r.ok && !r.tried))
            r.build(d, g_net_gpu_idx, g.w, g.h, OW, OH, target_fmt,
                    module_dir() + "\\" + kModelDirs[g_model_idx]);
        remote_now = r.ok;
    } else if (g_remote.ok || g_remote.tried) {
        g_remote.destroy(d);
        g_remote.tried = false;
        g_remote.adapter = -1;
        std::snprintf(g_remote_note, sizeof g_remote_note, "%s", "off");
    }
    if (g_net_gpu_idx >= 0 && !remote_api)
        std::snprintf(g_remote_note, sizeof g_remote_note, "%s",
                      "a second GPU needs a D3D11 or D3D12 game -- running on the game's GPU");

    // the network's inputs: Local Tone and Local Structure, as fp32 bits of percent / 100 (see
    // kStageHLSL)
    auto fbits = [](float f) { uint32_t b; std::memcpy(&b, &f, 4); return b; };
    const uint32_t stage_args[12] = {g.w, g.h, OW, OH, g.frame, fbits(float(g_tone) / 100.0f),
                                     fbits(float(g_structure) / 100.0f)};
    if (remote_now) {
        remote_slot = g_remote.step(d, cmd, g.src_copy, stage_args, g_remote.net.cout0 >= 12 ? group : 0u);
        // at present this is ReShade's own list, submitted here so the fence can follow it;
        // before the HUD it is the game's, and the fence goes in at the present event
        if (g.api == device_api::d3d12 && !g_in_preui) signal_remote_copy(rt->get_command_queue(), true);
    } else {
        // 1. the 16 input channels, at the network's resolution
        go2d(g.stage_pso, src_srv, {}, g.chans_uav, stage_args, g.w, g.h);

        // 2. the network
        resource_view cur_srv = g.chans_srv;
        resource_view a_srv = g.A_srv, a_uav = g.A_uav, b_srv = g.B_srv, b_uav = g.B_uav;
        uint32_t k = 0, hh = g.h, ww = g.w;
        auto conv = [&](const opennr::Conv& c, resource_view in, resource_view out_uav,
                        uint32_t W2, uint32_t H2, bool act, bool zero_pad = false,
                        resource_view bias = resource_view{}) {
            const uint32_t a[12] = {W2, H2, c.cin, c.pad, act ? 1u : 0u, zero_pad ? 1u : 0u};
            const uint32_t threads = (W2 * H2 / 4) * (c.pad / 4);
            go(g.conv_pso, in, c.w_srv, bias.handle ? bias : c.b_srv, out_uav, a,
               (threads + 63) / 64);
        };
        auto pool = [&](resource_view in, resource_view out_uav, uint32_t W2, uint32_t H2,
                        uint32_t C) {
            const uint32_t pa[12] = {W2, H2, C};
            const uint32_t n = (W2 / 2) * (H2 / 2) * (C / 4);
            go(g.pool_pso, in, {}, {}, out_uav, pa, (n + 63) / 64);
        };
        // 2a. the whole-frame branch, when the model has one: the frame averaged 8x8, three small
        // convolutions, their mean and two linear layers into the middle block's bias. It reads
        // only the input channels, so it runs first and leaves A and B free.
        if (g.net.glob) {
            uint32_t gw = g.w, gh = g.h;
            for (int s = 0; s < 3; ++s) {
                pool(cur_srv, b_uav, gw, gh, g.net.cin);
                std::swap(a_srv, b_srv); std::swap(a_uav, b_uav); cur_srv = a_srv;
                gw /= 2; gh /= 2;
            }
            for (size_t s = 0; s < g.net.gconvs.size(); ++s) {
                const opennr::Conv& c = g.net.gconvs[s];
                conv(c, cur_srv, b_uav, gw, gh, true, true);
                std::swap(a_srv, b_srv); std::swap(a_uav, b_uav); cur_srv = a_srv;
                if (s + 1 < g.net.gconvs.size()) {
                    pool(cur_srv, b_uav, gw, gh, c.pad);
                    std::swap(a_srv, b_srv); std::swap(a_uav, b_uav); cur_srv = a_srv;
                    gw /= 2; gh /= 2;
                }
            }
            const opennr::Conv& mid_a = g.net.convs[2 * g.net.levels];
            const uint32_t ga[12] = {gw * gh, g.net.g_in, g.net.g_hidden, g.net.g_out};
            go(g.glob_pso, cur_srv, g.net.fc_srv, mid_a.b_srv, g.gbias_uav, ga, 1);
            cur_srv = g.chans_srv;
        }
        // 2b. the encoder
        for (uint32_t i = 0; i < g.net.levels; ++i) {
            for (int j = 0; j < 2; ++j) {
                const opennr::Conv& c = g.net.convs[k++];
                const bool last = (j == 1);
                conv(c, cur_srv, last ? g.skip_uav[i] : b_uav, ww, hh, true);
                if (last) { cur_srv = g.skip_srv[i]; }
                else { std::swap(a_srv, b_srv); std::swap(a_uav, b_uav); cur_srv = a_srv; }
            }
            if (i + 1 < g.net.levels) {
                const uint32_t pa[12] = {ww, hh, g.net.base << i};
                const uint32_t n = (ww / 2) * (hh / 2) * (g.net.base << i);
                go(g.pool_pso, g.skip_srv[i], {}, {}, b_uav, pa, (n + 63) / 64);
                std::swap(a_srv, b_srv);
                std::swap(a_uav, b_uav);
                cur_srv = a_srv;
                ww /= 2;
                hh /= 2;
            }
        }
        // 2c. the middle block, whose first layer takes the whole-frame branch's bias
        for (int j = 0; j < 2; ++j) {
            const opennr::Conv& c = g.net.convs[k++];
            conv(c, cur_srv, b_uav, ww, hh, true, false,
                 (j == 0 && g.net.glob) ? g.gbias_srv : resource_view{});
            std::swap(a_srv, b_srv);
            std::swap(a_uav, b_uav);
            cur_srv = a_srv;
        }
        // 2d. the decoder
        for (int i = int(g.net.levels) - 1; i >= 0; --i) {
            const uint32_t sw = g.w >> i, sh = g.h >> i;
            const opennr::Conv& c0 = g.net.convs[k];
            const uint32_t cs = g.net.base << i;
            const uint32_t clo = c0.cin - cs;
            const uint32_t scale = (i + 1 < int(g.net.levels)) ? 2u : 1u;
            const uint32_t ua[12] = {sw, sh, clo, cs, scale};
            const uint32_t n = sw * sh * c0.cin;
            go(g.upcat_pso, cur_srv, g.skip_srv[i], {}, b_uav, ua, (n + 63) / 64);
            std::swap(a_srv, b_srv);
            std::swap(a_uav, b_uav);
            cur_srv = a_srv;
            ww = sw;
            hh = sh;
            for (int j = 0; j < 2; ++j) {
                const opennr::Conv& c = g.net.convs[k++];
                conv(c, cur_srv, b_uav, ww, hh, true);
                std::swap(a_srv, b_srv);
                std::swap(a_uav, b_uav);
                cur_srv = a_srv;
            }
        }
        conv(g.net.convs[k++], cur_srv, g.head_uav, g.w, g.h, false);   // the output layer
    }

    auto end_timing = [&] {
        if (!timed) return;
        cmd->end_query(g.timer, query_type::timestamp, g.slot * 2 + 1);
        g.slot_used[g.slot] = true;
        g.slot = (g.slot + 1) % Ctx::RING;
    };
    if (remote_now && remote_slot < 0) {
        // the first two frames on the other GPU: nothing has come back yet, so the frame goes out
        // as the game drew it
        end_timing();
        if (g.api != device_api::d3d11) g.settle(cmd);
        ++g.frame;
        return;
    }

    // 3. composite, lifting the correction back to the output resolution. With the network on the
    // other GPU the frame shown is the one its correction was computed from, two frames back;
    // that output arrives packed, one group of four channels a pixel.
    const resource_view comp_src = remote_now ? g_remote.frame_srv[remote_slot] : src_srv;
    const resource_view comp_head = remote_now ? g_remote.head_srv : g.head_srv;
    const uint32_t comp_args[12] = {g.w, g.h, OW, OH, g_strength,
                                    remote_now ? 4u : g.net.convs.back().pad, g_view,
                                    remote_now ? 0u : group,
                                    (g_model & 3u) | ((g_tone < 100u ? g_tone : 100u) << 8)};
    go2d(g.comp_pso, comp_src, comp_head, g.scratch_uav, comp_args, OW, OH);

    g.use(cmd, g.scratch, resource_usage::copy_source);
    cmd->barrier(target, resource_usage::render_target, resource_usage::copy_dest);
    cmd->copy_texture_region(g.scratch, 0, nullptr, target, 0, nullptr);
    cmd->barrier(target, resource_usage::copy_dest, resource_usage::render_target);

    end_timing();
    if (g.api != device_api::d3d11) g.settle(cmd);
    ++g.frame;
}

// ------------------------------------------------------------------------------ settings
void read_config() {
    unsigned int v = 100;
    reshade::get_config_value(nullptr, "OpenNR", "Strength", v);
    g_strength = v > 200 ? 200 : v;
    v = 100;
    reshade::get_config_value(nullptr, "OpenNR", "LocalTone", v);
    g_tone = v > 200 ? 200 : v;
    v = 100;
    reshade::get_config_value(nullptr, "OpenNR", "LocalStructure", v);
    g_structure = v > 200 ? 200 : v;
    v = 0;
    reshade::get_config_value(nullptr, "OpenNR", "CorrectionModel", v);
    g_model_idx = v >= kModelCount ? kModelCount - 1 : v;
    v = 0;
    reshade::get_config_value(nullptr, "OpenNR", "Model", v);
    g_model = v > 2 ? 2 : v;
    v = 1;
    reshade::get_config_value(nullptr, "OpenNR", "BeforeHUD", v);
    g_preui = v ? 1u : 0u;
    // stored by name, not index: indices move when hardware does, and the game's own adapter can
    // only be told apart once its device exists, so the name is resolved on the first frame
    size_t sz = sizeof g_net_gpu;
    if (!reshade::get_config_value(nullptr, "OpenNR", "NetworkGPU", g_net_gpu, &sz)) g_net_gpu[0] = '\0';
    g_net_gpu_pending = true;
}

// the adapter named `g_net_gpu` that is not the one the game runs on; -1 when there is none
void resolve_net_gpu(device* d) {
    g_net_gpu_pending = false;
    g_net_gpu_idx = -1;
    if (!g_net_gpu[0]) return;
    LUID mine{};
    const bool have = game_luid(d, &mine);
    for (const AdapterInfo& a : list_adapters())
        if (!a.software && a.name == g_net_gpu && !(have && same_luid(a.luid, mine))) {
            g_net_gpu_idx = a.index;
            return;
        }
    std::snprintf(g_remote_note, sizeof g_remote_note,
                  "\"%.120s\" is not in this system -- running on the game's GPU", g_net_gpu);
}

bool slider(const char* label, const char* key, uint32_t& val) {
    int v = int(val);
    if (!ImGui::SliderInt(label, &v, 0, 200)) return false;
    val = uint32_t(v < 0 ? 0 : (v > 200 ? 200 : v));
    reshade::set_config_value(nullptr, "OpenNR", key, val);
    return true;
}

void on_overlay(effect_runtime* rt) {
    ImGui::Text("OpenNR %s", kVersion);
    if (g.dev && g.api == device_api::vulkan)
        ImGui::TextDisabled("%s", "Vulkan support is experimental.");
    ImGui::Separator();

    // Which GPU runs the network: the game's own, or any other the system reports (software
    // adapters left out, and one entry per physical GPU).
    {
        static std::vector<AdapterInfo> ads;
        static ULONGLONG listed = 0;
        LUID mine{};
        const bool have = rt && game_luid(rt->get_device(), &mine);
        if (GetTickCount64() - listed > 5000) {
            ads.clear();
            for (const AdapterInfo& a : list_adapters()) {
                if (a.software || (have && same_luid(a.luid, mine))) continue;
                bool dup = false;
                for (const AdapterInfo& b : ads) dup = dup || same_luid(a.luid, b.luid);
                if (!dup) ads.push_back(a);
            }
            listed = GetTickCount64();
        }
        const char* cur = g_net_gpu_idx < 0 ? "the game's GPU" : g_net_gpu;
        if (ImGui::BeginCombo("Run the network on", cur)) {
            if (ImGui::Selectable("the game's GPU", g_net_gpu_idx < 0)) {
                g_net_gpu[0] = '\0';
                g_net_gpu_idx = -1;
                reshade::set_config_value(nullptr, "OpenNR", "NetworkGPU", "");
            }
            for (const AdapterInfo& a : ads)
                if (ImGui::Selectable(a.name.c_str(), g_net_gpu_idx == a.index)) {
                    std::snprintf(g_net_gpu, sizeof g_net_gpu, "%s", a.name.c_str());
                    g_net_gpu_idx = a.index;
                    reshade::set_config_value(nullptr, "OpenNR", "NetworkGPU", g_net_gpu);
                }
            ImGui::EndCombo();
        }
        if (g_net_gpu_idx >= 0 || g_net_gpu[0]) ImGui::TextWrapped("%s", g_remote_note);
        ImGui::TextDisabled("%s", "(a second GPU runs OpenNR while this one runs the game. The\n"
                            " picture is then shown two frames late. An integrated GPU is\n"
                            " usually too slow for this.)");
    }
    ImGui::Separator();

    bool pu = g_preui != 0;
    if (ImGui::Checkbox("Correct before the game draws its HUD", &pu)) {
        g_preui = pu ? 1u : 0u;
        reshade::set_config_value(nullptr, "OpenNR", "BeforeHUD", g_preui);
    }
    if (g_preui) {
        ImGui::TextWrapped("%s", g_preui_note);
        ImGui::TextDisabled("%s", "(when it is not active, the whole frame is corrected, HUD\n"
                            " included. While it is active, other ReShade effects also run\n"
                            " before the HUD.)");
    }
    ImGui::Separator();

    slider("Strength (%)", "Strength", g_strength);
    slider("Local Tone Strength (%)", "LocalTone", g_tone);
    slider("Local Structure Strength (%)", "LocalStructure", g_structure);
    ImGui::TextDisabled("%s", "(Local Tone acts mostly on colour, Local Structure mostly on local\n"
                        " contrast. 10-100% gives the most predictable results.)");

    ImGui::TextUnformatted("Model");
    int md = int(g_model);
    bool md_changed = false;
    ImGui::SameLine(); md_changed |= ImGui::RadioButton("A", &md, 0);
    ImGui::SameLine(); md_changed |= ImGui::RadioButton("B", &md, 1);
    ImGui::SameLine(); md_changed |= ImGui::RadioButton("C", &md, 2);
    if (md_changed) {
        g_model = uint32_t(md < 0 ? 0 : (md > 2 ? 2 : md));
        reshade::set_config_value(nullptr, "OpenNR", "Model", g_model);
    }
    ImGui::TextDisabled("%s", "(A: neutral. B: -0.1 EV, -25% contrast, -10% saturation.\n"
                        " C: -15% saturation. B and C scale with Local Tone, up to 100%.)");

    int mi = int(g_model_idx);
    if (ImGui::Combo("Correction Model", &mi, kModelLabels, int(kModelCount))) {
        g_model_idx = uint32_t(mi < 0 ? 0 : (mi >= int(kModelCount) ? int(kModelCount) - 1 : mi));
        reshade::set_config_value(nullptr, "OpenNR", "CorrectionModel", g_model_idx);
    }
    ImGui::TextDisabled("%s", "(2 passes is a stronger and differently shaped correction, not the\n"
                        " same one scaled up. Both cost the same GPU time.)");
    ImGui::Separator();

    const char* kViews[] = {"Final frame", "Correction x20", "Source (what OpenNR reads)"};
    int vw = int(g_view);
    if (ImGui::Combo("View", &vw, kViews, 3)) g_view = uint32_t(vw < 0 ? 0 : (vw > 2 ? 2 : vw));
    if (g_view == 1)
        ImGui::TextDisabled("%s", "(mid-grey is unchanged, brighter is added, darker is taken away)");

    ImGui::Text("Depth buffer: %s", g_depth_note);
    ImGui::TextDisabled("%s", "(for information only; OpenNR does not use depth. REJECTED means\n"
                        " ReShade's Generic Depth picked a shadow map or a mirror: in its\n"
                        " settings, set \"Aspect ratio heuristic\" to \"Similar aspect ratio\".)");

    if (g.ready) {
        ImGui::Separator();
        if (g.w == g.ow && g.h == g.oh)
            ImGui::Text("Resolution: %u x %u (the game's own)", g.w, g.h);
        else
            ImGui::Text("Resolution: the network runs at %u x %u, upscaled to %u x %u", g.w, g.h,
                        g.ow, g.oh);
        if (g_net_gpu_idx >= 0 && g_remote.ok) {
            ImGui::TextUnformatted("GPU time: on the other GPU (see above)");
        } else if (!g.timer.handle) {
            ImGui::TextUnformatted("GPU time: this driver reports no timestamps");
        } else if (g.untimed) {
            ImGui::TextUnformatted("GPU time: not measured while correcting before the HUD on "
                                   "D3D12");
        } else if (g.gpu_ms == 0.0) {
            ImGui::TextUnformatted("GPU time: measuring");
        } else {
            // the multiply-adds are fixed by the network and its resolution, so the rate follows
            double mac = 0.0;
            for (const opennr::Conv& c : g.net.convs)
                mac += 9.0 * c.cin * c.pad * double(g.w >> c.level) * double(g.h >> c.level);
            ImGui::Text("GPU time: %.2f ms  (%.1f GMAC a frame, %.0f GMAC/s)", g.gpu_ms, mac / 1e9,
                        mac / 1e9 / (g.gpu_ms / 1000.0));
        }
    } else if (g.failed) {
        ImGui::Separator();
        ImGui::TextUnformatted("Setup failed -- see ReShade.log. The frame is left untouched.");
    }
}

void on_destroy_runtime(effect_runtime* rt) {
    std::lock_guard<std::mutex> lk(g_frame_mutex);
    g_rt = rt;                            // the destroys below wait on its queue off D3D11
    release_blank_state();
    if (g.dev) g_remote.destroy(g.dev);   // its game-side copies live on this device too
    g_remote.tried = false;
    g.destroy();
    g_rt = nullptr;
}

}  // namespace

extern "C" __declspec(dllexport) const char* NAME = "OpenNR";
extern "C" __declspec(dllexport) const char* DESCRIPTION =
    "A small neural network that re-balances local tone, local contrast and colour of the game's "
    "picture. https://github.com/MakeDecisionWorth/OpenNR-ReShade";

BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID) {
    switch (reason) {
    case DLL_PROCESS_ATTACH:
        g_module = hModule;
        if (!reshade::register_addon(hModule)) return FALSE;
        reshade::register_event<reshade::addon_event::reshade_begin_effects>(on_begin_effects);
        reshade::register_event<reshade::addon_event::reshade_finish_effects>(on_finish_effects);
        reshade::register_event<reshade::addon_event::present>(on_present);
        // finding where the HUD starts, and on D3D12 the bindings to restore after correcting
        reshade::register_event<reshade::addon_event::bind_render_targets_and_depth_stencil>(on_bind_rt);
        reshade::register_event<reshade::addon_event::bind_viewports>(on_bind_vp);
        reshade::register_event<reshade::addon_event::bind_pipeline>(on_bind_pipe);
        reshade::register_event<reshade::addon_event::draw>(on_draw);
        reshade::register_event<reshade::addon_event::draw_indexed>(on_draw_indexed);
        reshade::register_event<reshade::addon_event::init_command_list>(on_init_list);
        reshade::register_event<reshade::addon_event::destroy_command_list>(on_destroy_list);
        reshade::register_event<reshade::addon_event::reset_command_list>(on_reset_list);
        reshade::register_event<reshade::addon_event::execute_command_list>(on_execute_list);
        reshade::register_event<reshade::addon_event::begin_render_pass>(on_begin_pass);
        reshade::register_event<reshade::addon_event::end_render_pass>(on_end_pass);
        reshade::register_event<reshade::addon_event::bind_descriptor_tables>(on_bind_tables);
        reshade::register_event<reshade::addon_event::push_constants>(on_push_consts);
        reshade::register_event<reshade::addon_event::push_descriptors>(on_push_descs);
        reshade::register_event<reshade::addon_event::destroy_effect_runtime>(on_destroy_runtime);
        read_config();
        reshade::register_overlay(nullptr, on_overlay);
        break;
    case DLL_PROCESS_DETACH:
        reshade::unregister_addon(hModule);
        break;
    }
    return TRUE;
}
